dynawo:
    homeDir: "WORKING_DIR/dynawo"

dynawo-simulation-default-parameters:
    parametersFile: "WORKING_DIR/Nordic.par"
    network.parametersFile: "WORKING_DIR/Network.par"
    network.parametersId: "Network"
    solver.type: SIM
    solver.parametersFile: "WORKING_DIR/Solver.par"
    solver.parametersId: "Solver"
