dynaflow: 
  homeDir: WORKING_DIR/dynaflow-launcher
  debug: true  

dynaflow-default-parameters: 
  svcRegulationOn: true
  shuntRegulationOn: true 
  automaticSlackBusOn: true 
  vscAsGenerators: true
  lccAsLoads: true 
  dsoVoltageLevel: 63.0 
  settingPath: WORKING_DIR/setting-1.xml
  assemblingPath: WORKING_DIR/assembling.xml
  timeStep: 2.6 